// v1 trainer catalog — 10 формул Егора, блок «Вращение по окружности».
// Parallel branch к v2 (`formulas.generated.ts`). IDs имеют суффикс `_e`,
// чтобы не коллидировать с v2 (kin.13..kin.22). `relatedFormulas` указывают
// только внутрь v1 — cross-reference на v2 запрещён.
//
// Источник содержания: tutor Egor, Google Sheet "Механика_v1" (rows 32-41).
// Content совпадает с v2 kin.13..kin.22 — Variant B: hand-craft как
// отдельный модуль вне auto-generation pipeline.

import type { Formula } from './types';
import type { BuildRecipe } from './recipes.generated';
import type { FormulaMutation } from './mutations.generated';

export const egorFormulas: Formula[] = [
  {
    id: 'kin.13_e',
    section: 'Кинематика',
    topic: 'Кинематика — Вращение по окружности',
    name: 'Частота вращения',
    buildTitle: 'Частота вращения через число оборотов и время',
    formula: '\\nu=\\frac{N}{t}',
    formulaPlain: 'ν = N / t',
    variables: [
      { symbol: 'ν', name: 'частота вращения', unit: 'Гц' },
      { symbol: 'N', name: 'число оборотов', unit: '' },
      { symbol: 't', name: 'время', unit: 'с' },
    ],
    physicalMeaning: 'Частота показывает, сколько полных оборотов тело совершает за секунду. Чем больше оборотов за то же время, тем выше частота вращения.',
    proportionality: { direct: ['N → ν'], inverse: ['t → ν'] },
    dimensions: '[1/T] = [1] / [T]',
    derivedFrom: 'Определение частоты вращения',
    whenToUse: [
      'Дано число оборотов за некоторое время',
      'Нужно найти частоту вращения в Гц',
      'Задачи на колёса, карусели, спутники, вращающиеся диски',
    ],
    commonMistakes: [
      'Путают частоту ν и период T',
      'Забывают перевести обороты в секунды',
      'Берут t одного оборота вместо времени всех N оборотов',
    ],
    relatedFormulas: ['kin.14_e', 'kin.15_e', 'kin.18_e', 'kin.19_e'],
    difficulty: 1,
    exam: 'ЕГЭ',
    memoryHook: 'Частота — в герцах: сколько оборотов в секунду. Делим число оборотов N на время t.',
  },
  {
    id: 'kin.14_e',
    section: 'Кинематика',
    topic: 'Кинематика — Вращение по окружности',
    name: 'Период вращения',
    buildTitle: 'Период вращения через время и число оборотов',
    formula: 'T=\\frac{t}{N}',
    formulaPlain: 'T = t / N',
    variables: [
      { symbol: 'T', name: 'период вращения', unit: 'с' },
      { symbol: 'N', name: 'число оборотов', unit: '' },
      { symbol: 't', name: 'время N оборотов', unit: 'с' },
    ],
    physicalMeaning: 'Период показывает, сколько времени занимает один полный оборот. Если за то же время тело делает больше оборотов, период становится меньше.',
    proportionality: { direct: ['t → T'], inverse: ['N → T'] },
    dimensions: '[T] = [T] / [1]',
    derivedFrom: 'Определение периода вращения',
    whenToUse: [
      'Дано время нескольких оборотов',
      'Нужно найти время одного оборота',
      'Переход от числа оборотов к периоду вращения',
    ],
    commonMistakes: [
      'Путают период и частоту',
      'Делят число оборотов на время вместо времени на число оборотов',
      'Забывают, что период — это время именно одного оборота',
    ],
    relatedFormulas: ['kin.13_e', 'kin.15_e', 'kin.16_e', 'kin.19_e'],
    difficulty: 1,
    exam: 'ЕГЭ',
    memoryHook: 'Период — время одного оборота в секундах. Делим общее время на количество оборотов N.',
  },
  {
    id: 'kin.15_e',
    section: 'Кинематика',
    topic: 'Кинематика — Вращение по окружности',
    name: 'Связь частоты и периода вращения',
    buildTitle: 'Связь частоты и периода вращения',
    formula: '\\nu=\\frac{1}{T}',
    formulaPlain: 'ν = 1 / T',
    variables: [
      { symbol: 'ν', name: 'частота вращения', unit: 'Гц' },
      { symbol: 'T', name: 'период вращения', unit: 'с' },
    ],
    physicalMeaning: 'Частота и период — обратные величины. Чем дольше длится один оборот, тем меньше оборотов тело успевает сделать за секунду.',
    proportionality: { direct: [], inverse: ['T → ν'] },
    dimensions: '[1/T] = [1] / [T]',
    derivedFrom: 'Связь определений периода и частоты',
    whenToUse: [
      'Нужно перейти от периода к частоте или наоборот',
      'В задаче дано время одного оборота',
      'Сначала нашли период, а дальше нужна частота',
    ],
    commonMistakes: [
      'Пишут ν = T вместо обратной зависимости',
      'Забывают, что единица частоты — Гц = 1/с',
      'Путают с формулой T = t/N',
    ],
    relatedFormulas: ['kin.13_e', 'kin.14_e', 'kin.19_e'],
    difficulty: 1,
    exam: 'ЕГЭ',
    memoryHook: 'Период и частота взаимно обратны. Если период растёт — частота падает, и наоборот.',
  },
  {
    id: 'kin.16_e',
    section: 'Кинематика',
    topic: 'Кинематика — Вращение по окружности',
    name: 'Линейная скорость при вращении',
    buildTitle: 'Линейная скорость при равномерном вращении',
    formula: 'v=\\frac{2\\pi R}{T}',
    formulaPlain: 'v = 2πR / T',
    variables: [
      { symbol: 'v', name: 'линейная скорость', unit: 'м/с' },
      { symbol: 'R', name: 'радиус окружности', unit: 'м' },
      { symbol: 'T', name: 'период вращения', unit: 'с' },
    ],
    physicalMeaning: 'За один оборот точка проходит длину окружности 2πR. Линейная скорость равна пути за оборот, делённому на время одного оборота.',
    proportionality: { direct: ['R → v'], inverse: ['T → v'] },
    dimensions: '[L/T] = [L] / [T]',
    derivedFrom: 'Определение скорости: v = путь / время, где путь за оборот равен 2πR',
    whenToUse: [
      'Движение по окружности с известным радиусом и периодом',
      'Нужно найти скорость точки на ободе',
      'Задачи на карусели, колёса, спутники и вращающиеся диски',
    ],
    commonMistakes: [
      'Забывают множитель 2π',
      'Путают период T и частоту ν',
      'Подставляют диаметр вместо радиуса',
    ],
    relatedFormulas: ['kin.14_e', 'kin.15_e', 'kin.19_e', 'kin.20_e', 'kin.21_e'],
    difficulty: 2,
    exam: 'ЕГЭ',
    memoryHook: 'За один оборот точка проходит длину окружности 2πR. Не теряй множитель 2π.',
  },
  {
    id: 'kin.17_e',
    section: 'Кинематика',
    topic: 'Кинематика — Вращение по окружности',
    name: 'Определение угла в радианах',
    buildTitle: 'Угол в радианах через длину дуги и радиус',
    formula: '\\phi=\\frac{l}{R}',
    formulaPlain: 'φ = l / R',
    variables: [
      { symbol: 'φ', name: 'угол поворота', unit: 'рад' },
      { symbol: 'l', name: 'длина дуги', unit: 'м' },
      { symbol: 'R', name: 'радиус окружности', unit: 'м' },
    ],
    physicalMeaning: 'Радианная мера угла показывает, сколько радиусов укладывается в соответствующей дуге. Чем длиннее дуга при том же радиусе, тем больше угол.',
    proportionality: { direct: ['l → φ'], inverse: ['R → φ'] },
    dimensions: '[1] = [L] / [L]',
    derivedFrom: 'Определение радианной меры угла',
    whenToUse: [
      'Дана длина дуги и радиус окружности',
      'Нужно перейти от дуги к углу в радианах',
      'Подготовка к формулам угловой скорости и вращения',
    ],
    commonMistakes: [
      'Путают радианы и градусы',
      'Переворачивают дробь и пишут φ = R/l',
      'Забывают, что радиан — безразмерная величина',
    ],
    relatedFormulas: ['kin.18_e', 'kin.19_e', 'kin.20_e'],
    difficulty: 2,
    exam: 'ЕГЭ',
    memoryHook: 'Угол в радианах = длина дуги ÷ радиус. Радиан безразмерен.',
  },
  {
    id: 'kin.18_e',
    section: 'Кинематика',
    topic: 'Кинематика — Вращение по окружности',
    name: 'Определение угловой скорости',
    buildTitle: 'Угловая скорость через угол поворота и время',
    formula: '\\omega=\\frac{\\phi}{t}',
    formulaPlain: 'ω = φ / t',
    variables: [
      { symbol: 'ω', name: 'угловая скорость', unit: 'рад/с' },
      { symbol: 'φ', name: 'угол поворота', unit: 'рад' },
      { symbol: 't', name: 'время', unit: 'с' },
    ],
    physicalMeaning: 'Угловая скорость показывает, на какой угол тело поворачивается за единицу времени. Чем больший угол пройден за то же время, тем больше ω.',
    proportionality: { direct: ['φ → ω'], inverse: ['t → ω'] },
    dimensions: '[1/T] = [1] / [T]',
    derivedFrom: 'Определение угловой скорости',
    whenToUse: [
      'Известен угол поворота за некоторое время',
      'Нужно перейти от геометрии вращения к кинематике',
      'Задачи, где удобно считать вращение в радианах',
    ],
    commonMistakes: [
      'Путают ω с линейной скоростью v',
      'Используют градусы вместо радиан без перевода',
      'Ставят время в числитель вместо знаменателя',
    ],
    relatedFormulas: ['kin.17_e', 'kin.19_e', 'kin.20_e'],
    difficulty: 1,
    exam: 'ЕГЭ',
    memoryHook: 'Угловая скорость — радианов в секунду. Угол поворота в числителе, время — в знаменателе.',
  },
  {
    id: 'kin.19_e',
    section: 'Кинематика',
    topic: 'Кинематика — Вращение по окружности',
    name: 'Связь угловой скорости и периода вращения',
    buildTitle: 'Связь угловой скорости и периода вращения',
    formula: '\\omega=\\frac{2\\pi}{T}',
    formulaPlain: 'ω = 2π / T',
    variables: [
      { symbol: 'ω', name: 'угловая скорость', unit: 'рад/с' },
      { symbol: 'T', name: 'период вращения', unit: 'с' },
    ],
    physicalMeaning: 'За один полный оборот тело поворачивается на угол 2π рад. Поэтому угловая скорость равна 2π, делённым на время одного оборота.',
    proportionality: { direct: [], inverse: ['T → ω'] },
    dimensions: '[1/T] = [1] / [T]',
    derivedFrom: 'Из определения угловой скорости: за один оборот φ = 2π',
    whenToUse: [
      'Дано время одного оборота',
      'Нужно найти угловую скорость вращения',
      'Переход от периода к угловым величинам',
    ],
    commonMistakes: [
      'Забывают множитель 2π',
      'Путают с формулой ν = 1/T',
      'Подставляют число оборотов вместо периода одного оборота',
    ],
    relatedFormulas: ['kin.14_e', 'kin.15_e', 'kin.18_e', 'kin.20_e', 'kin.22_e'],
    difficulty: 2,
    exam: 'ЕГЭ',
    memoryHook: 'За один оборот тело проходит угол 2π радиан. Не путай с ν = 1/T (там без 2π).',
  },
  {
    id: 'kin.20_e',
    section: 'Кинематика',
    topic: 'Кинематика — Вращение по окружности',
    name: 'Связь линейной и угловой скорости',
    buildTitle: 'Связь линейной и угловой скорости',
    formula: 'v=\\omega R',
    formulaPlain: 'v = ωR',
    variables: [
      { symbol: 'v', name: 'линейная скорость', unit: 'м/с' },
      { symbol: 'ω', name: 'угловая скорость', unit: 'рад/с' },
      { symbol: 'R', name: 'радиус окружности', unit: 'м' },
    ],
    physicalMeaning: 'Линейная скорость точки на окружности тем больше, чем быстрее растёт угол поворота и чем дальше точка находится от оси вращения.',
    proportionality: { direct: ['ω → v', 'R → v'], inverse: [] },
    dimensions: '[L/T] = [1/T] * [L]',
    derivedFrom: 'Следствие из формул v = l/t и φ = l/R',
    whenToUse: [
      'Известна угловая скорость и радиус',
      'Нужно найти скорость точки на ободе',
      'Переход между угловыми и линейными величинами',
    ],
    commonMistakes: [
      'Путают формулы v = ωR и a_цс = ω²R',
      'Забывают, что скорость зависит от радиуса',
      'Ставят R в знаменатель вместо умножения',
    ],
    relatedFormulas: ['kin.16_e', 'kin.18_e', 'kin.19_e', 'kin.21_e', 'kin.22_e'],
    difficulty: 2,
    exam: 'ЕГЭ',
    memoryHook: 'Линейная скорость растёт пропорционально радиусу, без квадрата. R умножается, не делится.',
  },
  {
    id: 'kin.21_e',
    section: 'Кинематика',
    topic: 'Кинематика — Вращение по окружности',
    name: 'Центростремительное ускорение (через линейную скорость)',
    buildTitle: 'Центростремительное ускорение через линейную скорость',
    formula: 'a_{\\text{цс}} = \\frac{v^2}{R}',
    formulaPlain: 'a_цс = v² / R',
    variables: [
      { symbol: 'a_цс', name: 'центростремительное ускорение', unit: 'м/с²' },
      { symbol: 'v', name: 'линейная скорость', unit: 'м/с' },
      { symbol: 'R', name: 'радиус окружности', unit: 'м' },
    ],
    physicalMeaning: 'Центростремительное ускорение направлено к центру окружности и отвечает за изменение направления скорости. При большей скорости оно быстро растёт, а при большем радиусе уменьшается.',
    proportionality: { direct: ['v² → a_цс'], inverse: ['R → a_цс (при фиксированном v)'] },
    dimensions: '[L/T²] = [L²/T²] / [L]',
    derivedFrom: 'Геометрический вывод из изменения вектора скорости',
    whenToUse: [
      'Движение по окружности с известной линейной скоростью',
      'Нужно найти ускорение при вращении',
      'Связь с центростремительной силой F = ma_цс',
    ],
    commonMistakes: [
      'Теряют квадрат скорости и пишут v/R',
      'Путают радиус и период',
      'Считают, что ускорение направлено по касательной, а не к центру',
    ],
    relatedFormulas: ['kin.16_e', 'kin.20_e', 'kin.22_e'],
    difficulty: 2,
    exam: 'ЕГЭ',
    memoryHook: 'Центростремительное ускорение зависит от КВАДРАТА скорости. Направлено к центру окружности.',
  },
  {
    id: 'kin.22_e',
    section: 'Кинематика',
    topic: 'Кинематика — Вращение по окружности',
    name: 'Центростремительное ускорение (через угловую скорость)',
    buildTitle: 'Центростремительное ускорение через угловую скорость',
    formula: 'a_{\\text{цс}}=\\omega^2R',
    formulaPlain: 'a_цс = ω²R',
    variables: [
      { symbol: 'a_цс', name: 'центростремительное ускорение', unit: 'м/с²' },
      { symbol: 'ω', name: 'угловая скорость', unit: 'рад/с' },
      { symbol: 'R', name: 'радиус окружности', unit: 'м' },
    ],
    physicalMeaning: 'Та же центростремительная ускоренность можно выразить через угловую скорость. Чем быстрее вращение и чем дальше точка от оси, тем больше ускорение к центру.',
    proportionality: { direct: ['ω² → a_цс', 'R → a_цс'], inverse: [] },
    dimensions: '[L/T²] = [1/T²] * [L]',
    derivedFrom: 'Следствие из связей v = ωR и a_цс = v^2/R',
    whenToUse: [
      'Известна угловая скорость вращения',
      'Нужно найти ускорение точки на окружности',
      'Удобно, когда в задаче нет линейной скорости, но есть ω или период',
    ],
    commonMistakes: [
      'Теряют квадрат угловой скорости и пишут ωR',
      'Путают эту формулу с v = ωR',
      'Считают, что при большем радиусе ускорение всегда меньше, хотя здесь при фиксированном ω оно больше',
    ],
    relatedFormulas: ['kin.18_e', 'kin.19_e', 'kin.20_e', 'kin.21_e'],
    difficulty: 2,
    exam: 'ЕГЭ',
    memoryHook: 'a_цс через угловую скорость: КВАДРАТ ω умножить на R. С ростом R при том же ω ускорение растёт.',
  },
];

export const EGOR_BUILD_RECIPES: Record<string, BuildRecipe> = {
  'kin.13_e': {
    displayFormula: '\\nu=\\frac{N}{t}',
    numeratorTokens: ['N'],
    denominatorTokens: ['t'],
  },
  'kin.14_e': {
    displayFormula: 'T=\\frac{t}{N}',
    numeratorTokens: ['t'],
    denominatorTokens: ['N'],
  },
  'kin.15_e': {
    displayFormula: '\\nu=\\frac{1}{T}',
    numeratorTokens: ['1'],
    denominatorTokens: ['T'],
  },
  'kin.16_e': {
    displayFormula: 'v=\\frac{2\\pi R}{T}',
    numeratorTokens: ['2\\pi', 'R'],
    denominatorTokens: ['T'],
  },
  'kin.17_e': {
    displayFormula: '\\phi=\\frac{l}{R}',
    numeratorTokens: ['l'],
    denominatorTokens: ['R'],
  },
  'kin.18_e': {
    displayFormula: '\\omega=\\frac{\\phi}{t}',
    numeratorTokens: ['\\phi'],
    denominatorTokens: ['t'],
  },
  'kin.19_e': {
    displayFormula: '\\omega=\\frac{2\\pi}{T}',
    numeratorTokens: ['2\\pi'],
    denominatorTokens: ['T'],
  },
  'kin.20_e': {
    displayFormula: 'v=\\omega R',
    numeratorTokens: ['\\omega', 'R'],
    denominatorTokens: [],
  },
  'kin.21_e': {
    displayFormula: 'a_{\\text{цс}} = \\frac{v^2}{R}',
    numeratorTokens: ['v^2'],
    denominatorTokens: ['R'],
  },
  'kin.22_e': {
    displayFormula: 'a_{\\text{цс}}=\\omega^2R',
    numeratorTokens: ['\\omega^2', 'R'],
    denominatorTokens: [],
  },
};

export const EGOR_SUPPORTED_BUILD_FORMULA_IDS: Set<string> = new Set(Object.keys(EGOR_BUILD_RECIPES));

export const EGOR_MUTATION_LIBRARY: Record<string, FormulaMutation[]> = {
  'kin.13_e': [
    { type: 'swap_fraction', latex: '\\nu = \\frac{t}{N}', hint: 'Частота равна числу оборотов за время, а не времени на один оборот.' },
    { type: 'swap_variable', latex: '\\nu = N \\cdot t', hint: 'При увеличении времени при том же числе оборотов частота уменьшается, поэтому t должно быть в знаменателе.' },
  ],
  'kin.14_e': [
    { type: 'swap_fraction', latex: 'T = \\frac{N}{t}', hint: 'Период равен времени одного оборота, значит время должно стоять в числителе.' },
    { type: 'swap_variable', latex: 'T = t \\cdot N', hint: 'Чем больше оборотов за фиксированное время, тем меньше период, а не больше.' },
  ],
  'kin.15_e': [
    { type: 'swap_fraction', latex: '\\nu = T', hint: 'Частота и период обратны друг другу, а не равны.' },
    { type: 'swap_variable', latex: '\\nu = \\frac{T}{1}', hint: 'Если период растёт, частота уменьшается, поэтому T должно стоять в знаменателе.' },
  ],
  'kin.16_e': [
    { type: 'swap_fraction', latex: 'v = \\frac{T}{2\\pi R}', hint: 'Скорость равна длине окружности, делённой на период, а не наоборот.' },
    { type: 'drop_coefficient', latex: 'v = \\frac{R}{T}', hint: 'За один оборот точка проходит 2πR, поэтому множитель 2π терять нельзя.' },
  ],
  'kin.17_e': [
    { type: 'swap_fraction', latex: '\\phi = \\frac{R}{l}', hint: 'Радианная мера угла равна длине дуги, делённой на радиус.' },
    { type: 'swap_variable', latex: '\\phi = l \\cdot R', hint: 'При увеличении радиуса при той же дуге угол уменьшается, поэтому R должно быть в знаменателе.' },
  ],
  'kin.18_e': [
    { type: 'swap_fraction', latex: '\\omega = \\frac{t}{\\phi}', hint: 'Угловая скорость равна углу поворота за время, а не времени на угол.' },
    { type: 'swap_variable', latex: '\\omega = \\phi \\cdot t', hint: 'При фиксированном угле большему времени соответствует меньшая угловая скорость.' },
  ],
  'kin.19_e': [
    { type: 'drop_coefficient', latex: '\\omega = \\frac{1}{T}', hint: 'За один оборот тело проходит угол 2π рад, поэтому множитель 2π обязателен.' },
    { type: 'swap_fraction', latex: '\\omega = \\frac{T}{2\\pi}', hint: 'При увеличении периода угловая скорость уменьшается, значит T должно быть в знаменателе.' },
  ],
  'kin.20_e': [
    { type: 'swap_variable', latex: 'v = \\frac{\\omega}{R}', hint: 'Чем больше радиус при той же угловой скорости, тем больше линейная скорость, поэтому R должно умножаться.' },
    { type: 'wrong_power', latex: 'v = \\omega R^2', hint: 'Линейная скорость растёт пропорционально радиусу, а не квадрату радиуса.' },
  ],
  'kin.21_e': [
    { type: 'wrong_power', latex: 'a_{\\text{цс}} = \\frac{v}{R}', hint: 'Центростремительное ускорение зависит от квадрата линейной скорости.' },
    { type: 'swap_variable', latex: 'a_{\\text{цс}} = \\frac{v^2}{T}', hint: 'В этой формуле нужен радиус окружности, а не период вращения.' },
  ],
  'kin.22_e': [
    { type: 'wrong_power', latex: 'a_{\\text{цс}} = \\omega R', hint: 'Центростремительное ускорение зависит от квадрата угловой скорости.' },
    { type: 'swap_variable', latex: 'a_{\\text{цс}} = \\frac{\\omega^2}{R}', hint: 'При фиксированной угловой скорости увеличение радиуса увеличивает ускорение, поэтому R должно быть в числителе.' },
  ],
};
