import type { Formula } from './types';

export const kinematicsFormulas: Formula[] = [
  {
    id: 'kin.01',
    section: 'kinematics',
    topic: 'Кинематика',
    name: 'Перемещение при равномерном движении',
    formula: 's = v \\cdot t',
    formulaPlain: 's = v·t',
    variables: [
      { symbol: 's', name: 'перемещение', unit: 'м' },
      { symbol: 'v', name: 'скорость', unit: 'м/с' },
      { symbol: 't', name: 'время', unit: 'с' },
    ],
    physicalMeaning: 'Путь при постоянной скорости пропорционален времени.',
    proportionality: { direct: ['s ~ v', 's ~ t'], inverse: [] },
    dimensions: '[м] = [м/с] · [с]',
    derivedFrom: 'определение скорости v = s/t',
    whenToUse: [
      'Тело движется равномерно и прямолинейно',
      'Скорость постоянна, нет ускорения',
    ],
    commonMistakes: ['Путают с формулой равноускоренного движения', 'Забывают перевести единицы'],
    relatedFormulas: ['kin.02'],
    difficulty: 1,
  },
  {
    id: 'kin.02',
    section: 'kinematics',
    topic: 'Кинематика',
    name: 'Средняя скорость',
    formula: 'v_{ср} = \\frac{s_{общ}}{t_{общ}}',
    formulaPlain: 'v_ср = s_общ / t_общ',
    variables: [
      { symbol: 'v_{ср}', name: 'средняя скорость', unit: 'м/с' },
      { symbol: 's_{общ}', name: 'общий путь', unit: 'м' },
      { symbol: 't_{общ}', name: 'общее время', unit: 'с' },
    ],
    physicalMeaning: 'Средняя скорость — отношение всего пути ко всему времени.',
    proportionality: { direct: ['v_ср ~ s_общ'], inverse: ['v_ср ~ 1/t_общ'] },
    dimensions: '[м/с] = [м] / [с]',
    derivedFrom: 'определение средней скорости',
    whenToUse: [
      'Тело проходит несколько участков с разными скоростями',
      'Нужно найти среднюю скорость на всём пути',
    ],
    commonMistakes: ['Средняя скорость ≠ среднее арифметическое скоростей'],
    relatedFormulas: ['kin.01'],
    difficulty: 1,
  },
  {
    id: 'kin.03',
    section: 'kinematics',
    topic: 'Кинематика',
    name: 'Скорость при равноускоренном движении',
    formula: 'v = v_0 + a \\cdot t',
    formulaPlain: 'v = v₀ + a·t',
    variables: [
      { symbol: 'v', name: 'конечная скорость', unit: 'м/с' },
      { symbol: 'v_0', name: 'начальная скорость', unit: 'м/с' },
      { symbol: 'a', name: 'ускорение', unit: 'м/с²' },
      { symbol: 't', name: 'время', unit: 'с' },
    ],
    physicalMeaning: 'Скорость линейно растёт (или падает) со временем при постоянном ускорении.',
    proportionality: { direct: ['v ~ t (при a=const)'], inverse: [] },
    dimensions: '[м/с] = [м/с] + [м/с²] · [с]',
    derivedFrom: 'определение ускорения a = Δv/Δt',
    whenToUse: [
      'Тело разгоняется или тормозит равномерно',
      'Дано ускорение и нужно найти скорость через время',
    ],
    commonMistakes: ['Забывают начальную скорость v₀'],
    relatedFormulas: ['kin.04', 'kin.06'],
    difficulty: 1,
  },
  {
    id: 'kin.04',
    section: 'kinematics',
    topic: 'Кинематика',
    name: 'Перемещение при равноускоренном движении',
    formula: 's = v_0 t + \\frac{a t^2}{2}',
    formulaPlain: 's = v₀t + at²/2',
    variables: [
      { symbol: 's', name: 'перемещение', unit: 'м' },
      { symbol: 'v_0', name: 'начальная скорость', unit: 'м/с' },
      { symbol: 'a', name: 'ускорение', unit: 'м/с²' },
      { symbol: 't', name: 'время', unit: 'с' },
    ],
    physicalMeaning: 'Перемещение складывается из равномерной части и вклада ускорения.',
    proportionality: { direct: ['s ~ t²'], inverse: [] },
    dimensions: '[м] = [м/с]·[с] + [м/с²]·[с²]',
    derivedFrom: 'интегрирование v(t) = v₀ + at',
    whenToUse: [
      'Дано ускорение, начальная скорость и время',
      'Тело разгоняется или тормозит, нужен путь',
    ],
    commonMistakes: ['Забывают делить на 2'],
    relatedFormulas: ['kin.03', 'kin.05', 'kin.06'],
    difficulty: 2,
  },
  {
    id: 'kin.05',
    section: 'kinematics',
    topic: 'Кинематика',
    name: 'Перемещение через среднюю скорость',
    formula: 's = \\frac{v + v_0}{2} \\cdot t',
    formulaPlain: 's = (v + v₀)/2 · t',
    variables: [
      { symbol: 's', name: 'перемещение', unit: 'м' },
      { symbol: 'v', name: 'конечная скорость', unit: 'м/с' },
      { symbol: 'v_0', name: 'начальная скорость', unit: 'м/с' },
      { symbol: 't', name: 'время', unit: 'с' },
    ],
    physicalMeaning: 'При равноускоренном движении средняя скорость = полусумме начальной и конечной.',
    proportionality: { direct: ['s ~ t'], inverse: [] },
    dimensions: '[м] = [м/с] · [с]',
    derivedFrom: 'v_ср = (v + v₀)/2 при a = const',
    whenToUse: [
      'Даны начальная и конечная скорости, нужен путь',
      'Нет ускорения напрямую, но есть обе скорости и время',
    ],
    commonMistakes: ['Забывают делить на 2'],
    relatedFormulas: ['kin.04'],
    difficulty: 1,
  },
  {
    id: 'kin.06',
    section: 'kinematics',
    topic: 'Кинематика',
    name: 'Формула без времени',
    formula: 'v^2 = v_0^2 + 2as',
    formulaPlain: 'v² = v₀² + 2as',
    variables: [
      { symbol: 'v', name: 'конечная скорость', unit: 'м/с' },
      { symbol: 'v_0', name: 'начальная скорость', unit: 'м/с' },
      { symbol: 'a', name: 'ускорение', unit: 'м/с²' },
      { symbol: 's', name: 'перемещение', unit: 'м' },
    ],
    physicalMeaning: 'Связь скоростей и пути без времени.',
    proportionality: { direct: ['v² ~ s'], inverse: [] },
    dimensions: '[м²/с²] = [м²/с²] + [м/с²]·[м]',
    derivedFrom: 'исключение t из v = v₀ + at и s = v₀t + at²/2',
    whenToUse: [
      'Нет времени в условии, но есть ускорение и путь',
      'Нужно связать скорость и перемещение напрямую',
    ],
    commonMistakes: ['Забывают множитель 2', 'Путают v и v²'],
    relatedFormulas: ['kin.03', 'kin.04'],
    difficulty: 2,
  },
  {
    id: 'kin.07',
    section: 'kinematics',
    topic: 'Кинематика',
    name: 'Высота свободного падения',
    formula: 'h = \\frac{g t^2}{2}',
    formulaPlain: 'h = gt²/2',
    variables: [
      { symbol: 'h', name: 'высота', unit: 'м' },
      { symbol: 'g', name: 'ускорение свободного падения', unit: 'м/с²' },
      { symbol: 't', name: 'время', unit: 'с' },
    ],
    physicalMeaning: 'Частный случай s = at²/2 при v₀ = 0 и a = g.',
    proportionality: { direct: ['h ~ t²'], inverse: [] },
    dimensions: '[м] = [м/с²]·[с²]',
    derivedFrom: 's = v₀t + at²/2, v₀ = 0, a = g',
    whenToUse: [
      'Тело падает с нулевой начальной скоростью',
      'Свободное падение без начальной скорости',
    ],
    commonMistakes: ['Забывают делить на 2'],
    relatedFormulas: ['kin.04', 'kin.08'],
    difficulty: 1,
  },
  {
    id: 'kin.08',
    section: 'kinematics',
    topic: 'Кинематика',
    name: 'Скорость свободного падения',
    formula: 'v = g \\cdot t',
    formulaPlain: 'v = g·t',
    variables: [
      { symbol: 'v', name: 'скорость', unit: 'м/с' },
      { symbol: 'g', name: 'ускорение свободного падения', unit: 'м/с²' },
      { symbol: 't', name: 'время', unit: 'с' },
    ],
    physicalMeaning: 'Частный случай v = v₀ + at при v₀ = 0 и a = g.',
    proportionality: { direct: ['v ~ t'], inverse: [] },
    dimensions: '[м/с] = [м/с²]·[с]',
    derivedFrom: 'v = v₀ + at, v₀ = 0, a = g',
    whenToUse: [
      'Тело падает, нужно найти скорость через время',
      'Свободное падение, начальная скорость ноль',
    ],
    commonMistakes: ['Путают с h = gt²/2'],
    relatedFormulas: ['kin.03', 'kin.07'],
    difficulty: 1,
  },
  {
    id: 'kin.09',
    section: 'kinematics',
    topic: 'Кинематика',
    name: 'Линейная скорость по окружности',
    formula: 'v = \\frac{2 \\pi R}{T}',
    formulaPlain: 'v = 2πR/T',
    variables: [
      { symbol: 'v', name: 'линейная скорость', unit: 'м/с' },
      { symbol: 'R', name: 'радиус', unit: 'м' },
      { symbol: 'T', name: 'период', unit: 'с' },
    ],
    physicalMeaning: 'За один оборот тело проходит длину окружности 2πR.',
    proportionality: { direct: ['v ~ R'], inverse: ['v ~ 1/T'] },
    dimensions: '[м/с] = [м] / [с]',
    derivedFrom: 'v = s/t, s = 2πR, t = T',
    whenToUse: [
      'Движение по окружности, даны радиус и период',
      'Нужна линейная скорость при вращении',
    ],
    commonMistakes: ['Забывают 2π'],
    relatedFormulas: ['kin.10', 'kin.11', 'kin.12'],
    difficulty: 2,
  },
  {
    id: 'kin.10',
    section: 'kinematics',
    topic: 'Кинематика',
    name: 'Период и частота',
    formula: 'T = \\frac{1}{\\nu}',
    formulaPlain: 'T = 1/ν',
    variables: [
      { symbol: 'T', name: 'период', unit: 'с' },
      { symbol: '\\nu', name: 'частота', unit: 'Гц' },
    ],
    physicalMeaning: 'Период — время одного полного оборота, обратная величина частоте.',
    proportionality: { direct: [], inverse: ['T ~ 1/ν'] },
    dimensions: '[с] = 1 / [Гц]',
    derivedFrom: 'определение периода и частоты',
    whenToUse: [
      'Нужно перевести частоту в период или наоборот',
      'Задана частота вращения',
    ],
    commonMistakes: ['Путают T и ν'],
    relatedFormulas: ['kin.09', 'kin.11'],
    difficulty: 1,
  },
  {
    id: 'kin.11',
    section: 'kinematics',
    topic: 'Кинематика',
    name: 'Угловая скорость',
    formula: '\\omega = \\frac{2\\pi}{T}',
    formulaPlain: 'ω = 2π/T',
    variables: [
      { symbol: '\\omega', name: 'угловая скорость', unit: 'рад/с' },
      { symbol: 'T', name: 'период', unit: 'с' },
    ],
    physicalMeaning: 'Угловая скорость — полный оборот 2π радиан за период T.',
    proportionality: { direct: [], inverse: ['ω ~ 1/T'] },
    dimensions: '[рад/с] = [рад] / [с]',
    derivedFrom: 'ω = Δφ/Δt, Δφ = 2π, Δt = T',
    whenToUse: [
      'Нужна угловая скорость вращения',
      'Дан период, требуется ω',
    ],
    commonMistakes: ['Забывают 2π, пишут ω = 1/T = ν'],
    relatedFormulas: ['kin.09', 'kin.10', 'kin.12'],
    difficulty: 2,
  },
  {
    id: 'kin.12',
    section: 'kinematics',
    topic: 'Кинематика',
    name: 'Центростремительное ускорение',
    formula: 'a_{цс} = \\frac{v^2}{R}',
    formulaPlain: 'a_цс = v²/R',
    variables: [
      { symbol: 'a_{цс}', name: 'центростремительное ускорение', unit: 'м/с²' },
      { symbol: 'v', name: 'линейная скорость', unit: 'м/с' },
      { symbol: 'R', name: 'радиус', unit: 'м' },
    ],
    physicalMeaning: 'Ускорение, направленное к центру, при движении по окружности.',
    proportionality: { direct: ['a_цс ~ v²'], inverse: ['a_цс ~ 1/R'] },
    dimensions: '[м/с²] = [м²/с²] / [м]',
    derivedFrom: 'геометрическое вычисление Δv при движении по дуге',
    whenToUse: [
      'Движение по окружности, нужно ускорение к центру',
      'Дана скорость и радиус, ищем центростремительное ускорение',
    ],
    commonMistakes: ['Путают v и v²', 'Путают R и T'],
    relatedFormulas: ['kin.09', 'kin.11'],
    difficulty: 2,
  },
];

const formulaMap = new Map<string, Formula>();
for (const f of kinematicsFormulas) {
  formulaMap.set(f.id, f);
}

export function getFormulaById(id: string): Formula | undefined {
  return formulaMap.get(id);
}

export function getRelatedFormulas(formulaId: string): Formula[] {
  const formula = formulaMap.get(formulaId);
  if (!formula) return [];
  return formula.relatedFormulas
    .map((relId) => formulaMap.get(relId))
    .filter((f): f is Formula => f !== undefined);
}
