// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back. Use to verify MCP connectivity to \u0421\u043E\u043A\u0440\u0430\u0442 AI.",
  inputSchema: {
    text: z.string().min(1).describe("Text to echo back.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: ({ text }) => ({
    content: [{ type: "text", text }]
  })
});

// src/lib/mcp/tools/get-current-user.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_current_user_default = defineTool2({
  name: "get_current_user",
  title: "Get current user",
  description: "Return the signed-in \u0421\u043E\u043A\u0440\u0430\u0442 AI user's profile (id, email, role). Useful as a first call to confirm authentication and detect the user's role (student / tutor / admin).",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    const userId = ctx.getUserId();
    const email = ctx.getUserEmail() ?? null;
    const db = supabaseForUser(ctx);
    const { data: profile, error: profileError } = await db.from("profiles").select("id, full_name, role, telegram_user_id").eq("id", userId).maybeSingle();
    if (profileError) {
      return {
        content: [{ type: "text", text: `Profile lookup failed: ${profileError.message}` }],
        isError: true
      };
    }
    const { data: roles } = await db.from("user_roles").select("role").eq("user_id", userId);
    const payload = {
      user_id: userId,
      email,
      profile: profile ?? null,
      roles: (roles ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vrsseotrfmsxpbciyqzc";
var mcp_default = defineMcp({
  name: "sokrat-ai-mcp",
  title: "\u0421\u043E\u043A\u0440\u0430\u0442 AI",
  version: "0.1.0",
  instructions: "Tools for the \u0421\u043E\u043A\u0440\u0430\u0442 AI tutoring platform. Call `get_current_user` first to confirm the signed-in user and their role. Use `echo` to verify connectivity.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, get_current_user_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
